insta/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('instagram.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^logout/$', views.logout, {"next_page": '/'}),
    url(r'^tinymce/', include('tinymce.urls')),
    # url(r'^comments/', include('django_comments.urls')),
    # url('likes/', include('likes.urls')),
]

instagram/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^$accounts/profile/$', views.profile, name='profile'),
    url(r'^search/', views.search_results, name='search_results'),
    url(r'^new/post$', views.new_post, name='new_post'),
    url(r'^profile/edit/$', views.edit, name='edit'),
    url(r'^like/(?P<post_id>\d+)$', views.like, name='like'),
    url(r'^save/(?P<post_id>\d+)$', views.save, name='save'),
    url(r'^follow_or_not/(?P<user_id>\d+)$', views.togglefollow, name='follow_or_not'),
    url(r'^unlike/(?P<post_id>\d+)$', views.unlike, name='unlike'),
    url(r'^user/(?P<user_id>\d+)$', views.user, name='aboutuser'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instagram/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from tinymce.models import HTMLField
from django.dispatch import receiver
from django.db.models.signals import post_save
from PIL import Image


# Create your models here.

class Post(models.Model):
    image = models.ImageField(upload_to='posts/')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    caption = HTMLField()
    post_date = models.DateTimeField(default=timezone.now)

    @property
    def get_comments(self):
        return self.comments.all()

    @property
    def count_likes(self):
        return self.photolikes.count()

    class Meta:
        ordering = ["-pk"]
    

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    name = models.TextField(default="Anonymous")
    image = models.ImageField(upload_to='profile_pics/', default='profile_pics/default.jpg')
    bio = models.TextField(default="Welcome Me!")

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

    @classmethod
    def find_profile(cls, name):
        return cls.objects.filter(user__username__icontains=name).all()

    def togglefollow(self, profile):
        if self.following.filter(followee=profile).count() == 0:
            Follows(followee=profile, follower=self).save()
            return True
        else:
            self.following.filter(followee=profile).delete()
            return False

    def like(self, photo):
        if self.mylikes.filter(photo=photo).count() == 0:
            Likes(photo=photo, user=self).save()

    def save_image(self, photo):
        if self.saves.filter(photo=photo).count() == 0:
            Saves(photo=photo, user=self).save()
        else:
            self.saves.filter(photo=photo).delete()

    def unlike(self, photo):
        self.mylikes.filter(photo=photo).all().delete()

    def post(self, form):
        image = form.save(commit=False)
        image.user = self
        image.save()

    @property
    def follows(self):
        return [follow.followee for follow in self.following.all()]

    @classmethod
    def search_by_name(cls,search_term):
            profile = cls.objects.filter(name__icontains=search_term)
            return profile

instagram/forms.py
from django import forms
from .models import *


# ......
class NewPostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ['user', 'post_date']
        widgets = {
            'tags': forms.CheckboxSelectMultiple(),
        }


class ProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget = forms.TextInput()

    class Meta:
        model = Profile
        fields = ('name', 'image', 'bio')


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ('user',)

instagram/views.py
from django.http  import HttpResponse,Http404
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import *
from django.template import RequestContext
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.
@login_required(login_url='/accounts/login/')
def index(request):
    c = RequestContext(request, {
        'likes': 'likes',
    })

    posts = Post.objects.all().order_by('-post_date')
    return render(request, 'index.html', locals())


@login_required(login_url='/accounts/login/')
def new_post(request):
    current_user = request.user
    if request.method == 'POST':
        form = NewPostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = current_user
            post.save()
        return redirect('index')
    else:
        form = NewPostForm()
    return render(request, 'new_post.html', {"form": form})


@login_required(login_url='/accounts/login/')
def profile(request):
    posts = Post.objects.all().order_by('-post_date')
    return render(request, 'profile.html', locals())


@login_required(login_url='/accounts/login/')
def mine(request):
    images = request.user.profile.posts.all()
    user_object = request.user
    user_images = user_object.profile.posts.all()
    user_saved = [save.photo for save in user_object.profile.saves.all()]
    user_liked = [like.photo for like in user_object.profile.mylikes.all()]
    print(user_liked)
    return render(request, 'myprofile.html', locals())


@login_required(login_url='/accounts/login/')
def edit(request):
    if request.method == 'POST':
        print(request.FILES)
        new_profile = ProfileForm(
            request.POST,
            request.FILES,
            instance=request.user.profile
        )
        if new_profile.is_valid():
            new_profile.save()
            print(new_profile.fields)
            # print(new_profile.fields.profile_picture)
            return redirect('profile')
    else:
        new_profile = ProfileForm(instance=request.user.profile)
    return render(request, 'edit.html', locals())


@login_required(login_url='/accounts/login/')
def user(request, user_id):
    user_object = get_object_or_404(User, pk=user_id)
    if request.user == user_object:
        return redirect('profile')
    user_images = user.posts.all()
    return render(request, 'profile.html', locals())

@login_required(login_url='/accounts/login/')
def like(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    request.user.profile.like(post)
    return JsonResponse(post.count_likes, safe=False)


@login_required(login_url='/accounts/login/')
def save(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    request.user.profile.save_image(post)
    return JsonResponse({}, safe=False)


@login_required(login_url='/accounts/login/')
def unlike(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    request.user.profile.unlike(post)
    return JsonResponse(post.count_likes, safe=False)


@login_required(login_url='/accounts/login/')
def togglefollow(request, user_id):
    target = get_object_or_404(User, pk=user_id).profile
    request.user.profile.togglefollow(target)
    response = [target.followers.count(), target.following.count()]
    return JsonResponse(response, safe=False)


def search_results(request):

    if 'profile' in request.GET and request.GET["profile"]:
        search_term = request.GET.get("profile")
        searched_profile = Profile.search_by_name(search_term)
        message = f"{search_term}"

        return render(request, 'search.html',{"message":message,"profile": searched_profile})

    else:
        message = "You haven't searched for any term"
        return render(request, 'search.html',{"message":message})

instagram/templates/edit.html
{%extends "layout.html" %}
{% load bootstrap3 %}
{% load static %}
{% block content %}
<div class="container mt-5">
	<div class="loginform">
		<form action="{%  url 'edit' %}" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			{% bootstrap_form new_profile %}
			<div class="form-group" style="text-align: center">
				<input type="submit" class="btn btn-success btn-md" value="Update">
			</div>
		</form>
	</div>
</div>
{% endblock %}

instagram/templates/index.html
{%extends 'layout.html'%}n
{% block content %}
<title>NAJINSTA</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<div class="container">
	<div class="row">
		<div class="col-md-8 justify-content-center">
			<ul id="myUL" class="list-unstyled">
				{% for post in posts %}
				<li class="filterDiv {{image.category}}">
					<div href="#"><span class="post-user">{{post.user}}</span>
					<div class="card rounded my-4">
						<div class="card-title m-0">
							<div class="user-head" href="{% url 'aboutuser' user_id=post.user.id %}">
								<button class="btn mx-3 bg-transparent btn-lg" data-toggle="tooltip" data-placement="bottom"
								        title="User">
									<img src="{{ user.profile.image.url }}" class="rounded-circle border" width="35" height="35"></button>
								<span class="username">{{post.user}}</span></div>
						</div>
						<img src="{{ post.image.url }}" class="img-fluid" alt="..." height="100%" width="100%">
						<div class="card-body">
							<div class="">
								<button class="btn bg-transparent image-icons toggle-like"><i class="far fa-heart no-color"></i>
								</button>
								<button class="btn bg-transparent image-icons btn-form"><i class="far fa-comment-alt"></i></button>
								
							</div>
							<div class="hidden-form">
								<hr class="mt-3">
							
								<hr class="mb-3">
							</div>
							<div class="ml-3">
								likes
							</div>
							{% autoescape on %}
							<div class="row ml-3"><span class="font-weight-bold mr-2">{{post.user}}</span>{{post.caption| safe}}</div>
							{% endautoescape %}
							<div class="text-muted">
								<p>Posted {{post.post_date|timesince}} ago ({{post.post_date}})</p>
							</div>
						</div>
						<div class="container ml-2">
						 %}
							<p>{{ comment_count }} comments.
								<button class="btn btn-md btn-info mx-5 btn-view">VIEW</button>
							</p>
							<div class="hidden-comments">
								
							</div>
						</div>
					</div>

					<div class="row">

					</div>
					<div>

					</div>

				</a></li>
				{% endfor %}
			</ul>
		</div>
		<div class="col-md-4">

		</div>
	</div>
</div>
{% endblock %}

instagram/templates/layout.html
{% load bootstrap3 %}
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">


	{%if title%}

	<title>{{title}}</title>

	{%endif%}
	{% block styles %}
	{% bootstrap_css %}
	{% endblock %}
	<link href="https://fonts.googleapis.com/css?family=Cookie&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
	<link rel="stylesheet" href="/static/css/animate.css">
	<link rel="stylesheet" href="/static/css/styles.css">

</head>

<body>
<div>
	{% include "navbar.html" %}
	{% if messages %}
	<ul class="messages">
		{% for msg in messages %}
		<li>
			<div class="alert alert-{{msg.level_tag}}" role="alert">
				{{msg.message}}
			</div>
		</li>
		{% endfor %}
	</ul>
	{% endif %}

	{% block content %} {%endblock%}

</div>
{% block scripts %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
{% bootstrap_javascript %}
{% endblock %}
<script src="/static/js/scripts.js"></script>
</body>

</html>

instagram/templates/navbar.html
<nav class="navbar sticky-top navbar-expand-lg navbar bg-white border-bottom">
	<div class="container animated fadeInDown slow">
		<!-- Image and text -->
		<nav class="navbar navbar-light">
			<a class="navbar-brand" href="/">
				<span class="icon-brand"><i class="fab fa-instagram mx-1"></i></span>
				<span class="vl"></span>
				<span class="brand-name">Instagram</span>
			</a>
		</nav>

		<div class="nav justify-content-center">
			<a href="{%url 'new_post'%}"><button class="btn mx-3 btn-transparent">
				<i class="fas fa-plus nav-icons"></i>
			</button></a>
        <form class="navbar-form" role="search" action="{% url 'search_results' %}">

          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search User" name="profile">
            <div class="input-group-btn">
              <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search">search</i></button>
            </div>
          </div>

        </form>
		</div>

		<button class="navbar-toggler ml-5" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03"
		        aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"><i class="fas fa-bars icon-brand"></i></span>
		</button>

		<div class="nav justify-content-end nav-icons">
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03"
			        aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarTogglerDemo03">
				{% if user.is_authenticated %}
				<button class="btn mx-2 bg-transparent btn-lg" data-toggle="tooltip" data-placement="bottom" title="Profile"><a
								href="accounts/profile/"><i class="far fa-user text-dark nav-icons"></i></a></button>
				<button class="btn mx-2 bg-transparent btn-lg" data-toggle="tooltip" data-placement="bottom"
				        title="Change Password"><a href="/accounts/password/change"><i
								class="fas fa-key nav-icons text-dark"></i></a></button>
				<button class="btn mx-2 bg-transparent btn-lg" data-toggle="tooltip" data-placement="bottom" title="Log Out"><a
								href="/logout"><i class="fas fa-times nav-icons text-dark"></i></a></button>
				{% else %}
				<button class="btn mx-2 bg-transparent btn-lg" data-toggle="tooltip" data-placement="bottom" title="Log In"><a
								href="/login"><i class="fas fa-times nav-icons text-dark"></i></a></button>
				{% endif %}
			</div>
		</div>
	</div>

</nav>

instagram/templates/new_post.html
{% extends 'layout.html' %}
{% load bootstrap3 %} {% load staticfiles %}

{% block content %}
<div class="container mt-5">
	<div class="card border p-5">
		<div class="card-header border-bottom">
      <h3>Post to Timeline</h3>
		</div>
		<form action="{%url 'new_post'%}" method="post" enctype="multipart/form-data">
			<div class="card-body border-0">
				{%csrf_token%}

				{% bootstrap_form form%}

			</div>
			<div class="card-footer border-top">
				<input type="submit" class="btn btn-success btn-lg animated pulse infinite slow" value="POST">

			</div>
		</form>
	</div>
</div>

{% endblock %}

instagram/templates/post.html
{% extends 'layout.html' %}
{% load bootstrap3 %}
{% block content %}

{% for post in user_images %}
<div style="background-image: url({{post.image.url}})" class="post col-6 col-sm-4 col-md-3">
    <div class="photoinfo">
        <div class="realphotoinfo">
            <span class="heartsmall instaicon"></span>
            <span class="infotext">{{post.photolikes.count}}</span>
            <span class="commentsmall instaicon"></span>
            <span class="infotext">{{post.comments.count}}</span>
        </div>
    </div>
</div>
{% endfor %}

{% endblock %}

instagram/templates/posts.html
{% extends 'layout.html' %}
{% load bootstrap3 %}
{% block content %}

{% for post in user_images %}
<div style="background-image: url({{post.image.url}})" class="post col-6 col-sm-4 col-md-3">
    <div class="photoinfo">
        <div class="realphotoinfo">
            <span class="heartsmall instaicon"></span>
            <span class="infotext">{{post.photolikes.count}}</span>
            <span class="commentsmall instaicon"></span>
            <span class="infotext">{{post.comments.count}}</span>
        </div>
    </div>
</div>
{% endfor %}

{% endblock %}

instagram/templates/profile.html
{% extends 'layout.html' %}
{% load bootstrap3 %}
{% block content %}
<div class="container-fluid">
	<div class="card mb-3 profile-card mt-5" style="max-width: 540px;">
		<div class="row no-gutters">
			<div class="col-md-4 rounded circle">
				<img src="{{ user.profile.image.url }}" class="card-img rounded-circle border responsive" alt="..." height="175">
			</div>
			<div class="col-md-8">
				<div class="card-body">
					<h1 class="card-title">{{ user.profile.user }}
						<a href="{%  url 'edit' %}" style="text-decoration: none;">
							<button class="btn mx-3">Edit Profile</button>
						</a>
						<button class="btn bg-transparent" data-toggle="modal" data-target="#exampleModalCenter"><i
										class="fas fa-cog nav-icons"></i></button>
					</h1>
					<p class="card-text">

						<span class="m-3">{{ user.post_set.count }} posts</span>
						<span class="m-3">followers</span>
						<span class="m-3">following</span>
					</p>
					<p class="font-weight-bold">{{ user.profile.name }}</p>
					<p class="">{{ user.profile.bio }}</p>
				</div>
			</div>
		</div>
	</div>
	<!--  image gallery-->
	<div class="container mt-5 image-container">
		<ul class="nav nav-tabs" id="myTab" role="tablist">
			<li class="nav-item profile-first-nav">
				<a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home"
				   aria-selected="true"><h4>POSTS</h4></a>
			</li>
			<li class="nav-item profile-img-nav">
				<a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile"
				   aria-selected="false"><h4>SAVED</h4></a>
			</li>
			<li class="nav-item profile-img-nav">
				<a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact"
				   aria-selected="false"><h4>OTHER</h4></a>
			</li>
		</ul>
		<div class="tab-content" id="myTabContent">
			<div class="tab-pane animated fadeIn slow show active" id="home" role="tabpanel" aria-labelledby="home-tab">
				{% for post in posts %}
				{% if post.user == user.profile.user %}
				<img src="{{ post.image.url }}" class='responsive m-3' height="300" width="300">
				{% endif %}
				{% endfor %}
			</div>
			<div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
				<div class="animated fadeIn slow">
					SAVED POSTS GO HERE
				</div>
			</div>
			<div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
				<div class="animated fadeIn slow">
					OTHER SECTION
				</div>
			</div>
		</div>
	</div>
</div>

<!-- Modal -->
<div class="modal animated fadeInDown slow rounded" id="exampleModalCenter" tabindex="-1" role="dialog"
     aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-body text-center">
				<a href="/logout">
					<button type="button" class="btn bg-transparent" data-dismiss="modal">Log Out</button>
				</a>
				<hr>
				<a href="#" data-dismiss="modal">
					<button type="button" class="btn bg-transparent">Cancel</button>
				</a>
			</div>
		</div>
	</div>
</div>
{% endblock %}

instagram/templates/search.html
{% block content %}
<div class="container">

  <div class="row">
    {% if profile %}
      <h2>Found {{ profile|length }} of searched term {{message}}</h2>
    {% else %}
      <h2> Found 0 profile for the search term {{message}}</h2>
    {% endif %}

  </div>

  <div class="row">

  {% if profile %}
    {% for profile in profile %}
      <div class="col-sm-6 col-md-3">
      <a href='{% url 'profile' %}'><h1>{{profile.name}}</h1>
</a>
      </div>
    {% endfor %}
  {% endif %}
  </div>
</div>
{% endblock %}